name: 'Update image tag'
description: 'Update image tag'
inputs:
  image-tag:
    description: 'Image tag'
    default: ${{ github.sha }}
    required: false
  update-deployment-list:
    description: 'List of deployment where image tag should be updated'
    default: |
      **
    required: false
outputs:
  image-tag:
    description: 'Image tag'
    value: ${{ steps.image-metadata.outputs.image-tag }}

runs:
  using: 'composite'
  steps:
    - id: image-metadata
      name: Extract image metadata
      env:
        UPDATE_DEPLOYMENT_LIST: ${{ inputs.update-deployment-list }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        
        if [[ -n "$UPDATE_DEPLOYMENT_LIST" ]]; then
            while IFS= read -r line; do
              if [[ -n "$line" ]]; then
                echo "Update folder: deploy/overlays/staging/${line}/image.yaml"
                sed -ri "s~image: (.*):(.*)~image: \1:${{github.sha}}~g" deploy/overlays/staging/${line}/image.yaml
                cat deploy/overlays/staging/${line}/image.yaml
              fi
            done <<< "$UPDATE_DEPLOYMENT_LIST"
        fi
      
      shell: bash
      
