name: 'Update image tag'
description: 'Update image tag'
inputs:
  image-tag:
    description: 'Image tag'
    default: ${{ github.sha }}
    required: false
  update-deployment-list:
    description: 'List of deployment where image tag should be updated'
    default: |
      deploy/overlays/staging
    required: false
outputs:
  image-tag:
    description: 'Image tag'
    value: ${{ steps.image-metadata.outputs.image-tag }}

runs:
  using: 'composite'
  steps:
    - id: image-metadata
      name: Extract image metadata
      env:
        UPDATE_DEPLOYMENT_LIST: ${{ inputs.update-deployment-list }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        
        if [[ -n "$UPDATE_DEPLOYMENT_LIST" ]]; then
            echo "Adding UPDATE_DEPLOYMENT_LIST to file: $UPDATE_DEPLOYMENT_LIST"
            echo "$UPDATE_DEPLOYMENT_LIST" > update-deployment-list.env
            while IFS= read -r line; do
              echo "In Loop ${line}"
              if [[ -n "$line" ]]; then
                echo "Update folder: ${line}/**/image.yaml"
              fi
            done <<< "$UPDATE_DEPLOYMENT_LIST"
        fi

        echo "Done"
      
      shell: bash
      
