name: 'ArgoCD staging auto deployment - Image tag updater'
description: 'Action to update image TAG in all deploy/overlays/staging/**/image.yaml e.g. gcr.io/platform-abc/consumer:TAG'
inputs:
  image-tag:
    description: 'Image tag'
    default: ${{ github.sha }}
    required: false
  update-deployment-list:
    description: 'List of deployments where image tag should be updated, by default `**` to udpate all deployments'
    default: |
      **
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Update image tag
      env:
        UPDATE_DEPLOYMENT_LIST: ${{ inputs.update-deployment-list }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        
        if [[ -n "$UPDATE_DEPLOYMENT_LIST" ]]; then
            while IFS= read -r line; do
              if [[ -n "$line" ]]; then
                 
                 if [ "$line" != "**" ] && [ ! -f "deploy/overlays/staging/$line/image.yaml" ]; then
                    echo "deploy/overlays/staging/${line}/image.yaml doesn't exists."
                    break
                 fi
                 
                echo "Update folder: deploy/overlays/staging/${line}/image.yaml"
                sed -ri "s~image: (.*):(.*)~image: \1:${{github.sha}}~g" deploy/overlays/staging/${line}/image.yaml
                cat deploy/overlays/staging/${line}/image.yaml | grep "image:"
              fi
            done <<< "$UPDATE_DEPLOYMENT_LIST"
        fi
      shell: bash
      
