name: 'Image tag updater - ArgoCD staging auto deployment'
description: 'Action to update image TAG in all deploy/overlays/staging/**/image.yaml e.g. gcr.io/platform-abc/consumer:TAG'
inputs:
  image-tag:
    description: 'Image tag'
    default: ${{ github.sha }}
    required: false
  update-deployment-list:
    description: 'List of deployments where image tag should be updated, by default `**` to udpate all deployments'
    default: |
      **
    required: false
  deployment-path: 
    description: 'List of deployments where image tag should be updated, by default `**` to udpate all deployments'
    required: true
    default: "./deploy/overlays/staging"
  gcr-platform:
    description: 'GCR platform name e.g. platform-staging, platform-production'
    required: true
    default: 'gcr.io/platform-staging-200307/'
runs:
  using: 'composite'
  steps:
    - name: Update image tag
      env:
        UPDATE_DEPLOYMENT_LIST: ${{ inputs.update-deployment-list }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        DEPLOYMENT_PATH: ${{ inputs.deployment-path }}
        GCR_PLATFORM: ${{ inputs.gcr-platform }}
        UPDATED_TAG: false
      run: |
        if [[ -n "$UPDATE_DEPLOYMENT_LIST" ]]; then
          while IFS= read -r line; do
            if [[ -n "$line" ]]; then 
               IMAGE_FILE="$DEPLOYMENT_PATH/$line/image.yaml"   
               if [ "$line" != "**" ] && [ ! -f "$IMAGE_FILE" ]; then
                  echo "Error: Failed to update $IMAGE_FILE, file doesn't exists."
                  continue
               fi
              echo "Updating $IMAGE_FILE"
              echo "Previous TAG:"
              cat $IMAGE_FILE | grep "image:" 
              
              sed -ri "s~image: (${{env.GCR_PLATFORM}}.*):(.*)~image: \1:${{env.IMAGE_TAG}}~g" $IMAGE_FILE

              echo "New TAG:"
              cat $IMAGE_FILE | grep "image:"
              echo " "
            fi            
          done <<< "$UPDATE_DEPLOYMENT_LIST"
          
          if [[ ! -z $(git status -s) ]]; then   
            echo "UPDATED_TAG=true" >> $GITHUB_ENV
          else
            echo "There was no change in image tag"
          fi
    
        fi
      shell: bash
    - name: Commit image update changes
      if: env.UPDATED_TAG 
      run: |
        git config --global user.name 'argocd-image-updater'
        git config --global user.email 'argocd-image-updater@users.noreply.github.com'
        git commit -am "build: automatic update of argocd deployment" -m "updated image tag to '${{env.IMAGE_TAG}}'"
        git push 
      shell: bash   
